apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idoc
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - storage.yaml
  - services.yaml
  - deployments.yaml
