apiVersion: v1
kind: Secret
metadata:
  name: idoc-secrets
  namespace: idoc
type: Opaque
stringData:
  admin-jwt-secret: "e6bc72b23111324b49dd724eceb1fe919578282df1186414e47358c9175f98b83bb3ab709a4fe57f3ab77c86b72b1372120c2a07af9a41c6a23e9ecc33b580a9"
  doctor-jwt-secret: "93bdedfeaf709e9c32bcec06747701c5efcbcc8092586ec371771481acbd600108d9779b59ddaf7126eda9e28ca8801a592491cf2d33b9ac94e3ca1f8778cbcd"
  patient-jwt-secret: "43ec19abe3131f4568e6ddd018e09232f9ef0333c2ee9a6090632ffc2a1f62004d29c2dc50d46b80d864ec8701b0117f8203449d051e9a02bf4b24ac66eb54d2"
  notification-admin-jwt-secret: "admin_service_jwt_secret_123"
  notification-doctor-jwt-secret: "377eabfaad3828bb4a5319649dd5b256b3e308882b0ed1a6a1f8e104270bd6ff9d24991aa72ee93dfb53e6e1ab96778e54f03e361dd5d1e8cf757316028dbdec"
  notification-patient-jwt-secret: "your_patient_service_secret_key_123456789"
  jwt-expires-in: "7d"
  internal-service-secret: "idoc_internal_secret_2026_xyz123"
  admin-email: "admin@idoc.com"
  admin-password: "Admin123@"
  doctor-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/doctor_service_db"
  patient-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/patient_service_db"
  appointment-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/idoc_appointment"
  payment-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/idoc_payment"
  telemedicine-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/idoc_telemedicine"
  notification-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/notification_service_db"
  ai-symptoms-mongo-uri: "mongodb+srv://IDOC:IDOC123@cluster0.x1rq5u9.mongodb.net/ai-symptom-service"
  stripe-secret-key: "sk_test_51T52dbFeOBgbBhEDZQhkZOpmElLQ8oDmZB4UwRKucFPxbQdEW5xyrA5iRMb9hEG6mnh8KwyvdJkhajOrWXNgsfRw00qNpr1c7D"
  stripe-publishable-key: "pk_test_51T52dbFeOBgbBhED2kg9pfFZPSetGvwcHVa6bDBXiHR6fAqRZmAtMPGn0RlffVRJvl8bnQ4Zs3aKznooyzCdtDl900FgJ9JrLU"
  smtp-host: "smtp.gmail.com"
  smtp-port: "587"
  smtp-user: "shadowkl914@gmail.com"
  smtp-pass: "ushjaofgkvrjmkoa"
  email-from: "iDoc <shadowkl914@gmail.com>"
  openrouter-api-key: "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"
